brew formula

diff --git a/docker-compose-magento b/docker-compose-magento
--- a/docker-compose-magento
+++ b/docker-compose-magento
@@ -2,12 +2,31 @@
 set -e
 #set -x
 
+DIR=$(dirname $0)
+
+find-up () {
+  path=${2-$(pwd)}
+  while [[ "$path" != "" && ! -e "$path/$1" ]]; do
+    path=${path%/*}
+  done
+  echo "$path"
+}
+
+if [[ -z $COMPOSE_PROJECT_APPDIR ]]; then
+  COMPOSE_PROJECT_APPDIR=$(find-up composer.json $(pwd)/www)
+fi
+
+if [[ -z $COMPOSE_PROJECT_APPDIR ]]; then
+  echo "Application root folder not found, terminating..."
+  exit 1
+fi
+
+cd "$COMPOSE_PROJECT_APPDIR"
+
 if [[ -f .dockenv ]]; then
   set -o allexport
   source .dockenv
   set +o allexport
-else
-  cd $(dirname $0)
 fi
 
 if [[ -f .env ]]; then
@@ -18,7 +37,7 @@ fi
 
 export COMPOSE_PROJECT_MODE=${COMPOSE_PROJECT_MODE-default}
 export COMPOSE_PROJECT_PHP_VERSION=${COMPOSE_PROJECT_PHP_VERSION-7.4}
-export COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME-$(basename $(pwd))}
+export COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME-$(basename "$COMPOSE_PROJECT_APPDIR")}
 export COMPOSE_PROJECT_PORT_PREFIX=${COMPOSE_PROJECT_PORT_PREFIX-"302"}
 export COMPOSE_PROJECT_PORT_HTTP=${COMPOSE_PROJECT_PORT_HTTP-"${COMPOSE_PROJECT_PORT_PREFIX}80"}
 export COMPOSE_PROJECT_PORT_XHGUI=${COMPOSE_PROJECT_PORT_XHGUI-"${COMPOSE_PROJECT_PORT_PREFIX}81"}
@@ -26,34 +45,29 @@ export COMPOSE_PROJECT_PORT_MYSQL=${COMPOSE_PROJECT_PORT_MYSQL-"${COMPOSE_PROJEC
 export COMPOSE_PROJECT_PORT_ELASTICSEARCH=${COMPOSE_PROJECT_PORT_ELASTICSEARCH-"${COMPOSE_PROJECT_PORT_PREFIX}92"}
 export COMPOSE_PROJECT_PORT_MAIL_WEBGUI=${COMPOSE_PROJECT_PORT_MAIL_WEBGUI-"${COMPOSE_PROJECT_PORT_PREFIX}25"}
 export COMPOSE_PROJECT_COMPOSER_AUTH=${COMPOSE_PROJECT_COMPOSER_AUTH-${COMPOSER_AUTH-""}}
-export COMPOSE_PROJECT_APPDIR=${COMPOSE_PROJECT_APPDIR-$(pwd)/www}
 
 DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN-$(which docker-compose)}";
-if [[ -f "docker-compose.yml" ]]; then
-  DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN} -f docker-compose.yml"
+if [[ -f "${DIR}/docker-compose.yml" ]]; then
+  DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN} -f ${DIR}/docker-compose.yml"
 fi
 
 if [[ "$COMPOSE_PROJECT_MODE" == "mutagen" ]]; then
-  if [[ -f "docker-compose-mutagen.yml" ]]; then
-      DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN} -f docker-compose-mutagen.yml"
+  if [[ -f "${DIR}/docker-compose-mutagen.yml" ]]; then
+      DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN} -f ${DIR}/docker-compose-mutagen.yml"
   fi
 else
   if [[ "$OSTYPE" == "darwin"* ]] && ps aux | grep -v 'grep' | grep nfsd > /dev/null 2>&1; then
-    if [[ -f "docker-compose-macos.yml" ]]; then
-      DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN} -f docker-compose-macos.yml"
-    fi
-  else
-    if [[ -f "docker-compose-bind.yml" ]]; then
-      DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN} -f docker-compose-bind.yml"
+    if [[ -f "${DIR}/docker-compose-macos.yml" ]]; then
+      DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN} -f ${DIR}/docker-compose-macos.yml"
     fi
   fi
 fi
 
-if [[ ! -d www ]]; then
-  mkdir www
+if [[ ! -d "$COMPOSE_PROJECT_APPDIR" ]]; then
+  mkdir -p "$COMPOSE_PROJECT_APPDIR"
 fi
 
-if [[ $COMPOSE_PROJECT_MODE == "mutagen" ]] && [[ -f "docker-compose-mutagen.yml" ]]; then
+if [[ $COMPOSE_PROJECT_MODE == "mutagen" ]] && [[ -f "${DIR}/docker-compose-mutagen.yml" ]]; then
   WAIT_SYNC="1"
   if docker volume ls | grep "^${COMPOSE_PROJECT_NAME}_appcode$" > /dev/null 2>&1; then
     if [[ $(docker volume inspect -f '{{ .Options.type }}' ${COMPOSE_PROJECT_NAME}_appcode) == "nfs" ]]; then
@@ -71,18 +85,19 @@ if [[ $COMPOSE_PROJECT_MODE == "mutagen" ]] && [[ -f "docker-compose-mutagen.yml
       ${DOCKER_COMPOSE_BIN} up -d mutagen
     fi
     DOCKER_CONTAINER_NAME_MUTAGEN=$(docker inspect -f '{{.Name}}' $(${DOCKER_COMPOSE_BIN} ps -q mutagen) | cut -c2-)
-    if ! mutagen sync list | grep -i "Name: ${COMPOSE_PROJECT_NAME}-appcode" > /dev/null 2>&1; then
-      mutagen sync create --sync-mode=two-way-resolved --ignore-vcs --symlink-mode=ignore --name=${COMPOSE_PROJECT_NAME}-appcode $(pwd)/www docker://linuxbrew@${DOCKER_CONTAINER_NAME_MUTAGEN}/var/www
+    MUTAGEN_SESSION_NAME=$(echo ${COMPOSE_PROJECT_NAME}-appcode | awk '{print tolower($0)}' | sed 's/[^0-9a-z]/-/g')
+    if ! mutagen sync list | grep -i "Name: ${MUTAGEN_SESSION_NAME}" > /dev/null 2>&1; then
+      mutagen sync create --sync-mode=two-way-resolved --ignore-vcs --symlink-mode=ignore --name=${MUTAGEN_SESSION_NAME} "$COMPOSE_PROJECT_APPDIR" docker://linuxbrew@${DOCKER_CONTAINER_NAME_MUTAGEN}/var/www
     else
       WAIT_SYNC=""
     fi
 
     if [[ $WAIT_SYNC == "1" ]]; then
-      until mutagen sync list "${COMPOSE_PROJECT_NAME}-appcode" | grep 'Status:' | grep 'Watching for changes' > /dev/null 2>&1; do
+      until mutagen sync list "${MUTAGEN_SESSION_NAME}" | grep 'Status:' | grep 'Watching for changes' > /dev/null 2>&1; do
         if which tput > /dev/null 2>&1; then
           tput cuu 1 && tput el
         fi
-        mutagen sync list "${COMPOSE_PROJECT_NAME}-appcode" | grep 'Status:' | echo $(awk -F: '{ print $2 }')
+        mutagen sync list "${MUTAGEN_SESSION_NAME}" | grep 'Status:' | echo $(awk -F: '{ print $2 }')
         sleep 3
       done
     fi
